language: ruby
rvm:
- 2.2.3
before_script:
- psql -c 'create database vocapp_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: G/kHnLay6xvBcvoty9XxABKJnYFXNwbBsJ76d67Pp//6HiQOxrT6d89hjE+muqrldCKr2yjBAnb+ORrLk0JuxlzY5kSU8/6zL2jE8v3sxMS8G3y8gntj3EABdubt851O3v8EgbIO+AwOspiggshPOo6dyu3Fo1ru0wGex1hRS8gVp1waEXHIul0iVdG5j8VbOnKoyBbjMqwBIzXBV0EktLJ215VbgkwYWmEnKmTfSy163xjFlDX8UFsCFMscTpGXHsSiuyJxcgv2JqKCgEWjczQUgpyNvemvubiZt9N4+R5EHyQn6ehnzhDaOJIbhrioqxjH3Eelq3oGLRof8GR4CcoM8+bjKmyEQcBp1GNbPC4w3wkglZfpuMrb4J4UHvP0/W1i1c05rKFDfTrmCHYYEfCnfjkNABxOAF7Ftt1ih6R5Gg6HHLs/K7+SVy0tKO8Np80bQidu4tcZVI5r7gwPMOrkmlJCRkWS8oXiRXkm+knOM9VqY4CtplbLRr7XRkeqvS6DMoMr3p2YAaNudFNGCy/mU0WmO3Hfwqw7/iD3ZnDu1Esi6K1IFwrBwB0qFkKYKnA/dSPJOBDd44Krp3ZZv7KJSwZHhhJs6yHCrb6s1MEQjl22w6o2H/FlKzGrIUdzTuq4Dpn2nh6032ebFF72bXnrL6/MzrS+ElTQP2vAD/E=
  app: vocabulary-app
  on:
    repo: empowerhack/vocapp
    branch: prototype-v0.1
