# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb17bc7343f30f210c011d1063cdf0891057f73ce48082ca75738461b2014bad53639b2a6c72e01cc2bf7b0bb65db4ee13246c9dcd9cfdb0227d9e3deb8bbd45
  facebook_app_id: '547701085431571'
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 35e86f09a76d4c3e9be3596b8bc78b6c41c175cdcd64f27524aa4e20f5910e613bc53fe05b1171be8fcc26979105af109adcbc9e7a8a8cb129c275e2b574cbfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
